### ISSUE TITLE
L'année 2024-2025 n'est pas encore dispo 

### ISSUE THREAD

**Issue by 4rnoP** [ADE-Scheduler/ADE-Scheduler#1050]
La nouvelle année académique 2024-2025 n'est toujours pas disponible sur ADE Scheduler, malgré qu'elle le soit sur l'outil officiel ADE UCL.

Ça pourrait être bien de la rendre disponible rapidement pour déjà avoir un aperçu de son horaire et éventuellement choisir certains cours en fonction.

**Comment by jeertmans** [comment]
Bonjour, nous sommes bien au courant de ce souci. Malheureusement, l'outil ADE Scheduler subit quelques changements assez importants ces derniers jours, réalisés par d'autres personnes que moi et Gilles, et je ne peux pas te promettre de date exacte pour la disponibilité, mais nous faisons au plus vite.

**Comment by jeertmans** [comment]
Il est fort possible que cela doive attendre le 9 septembre, vraiment désolé pour ça :/
