### ISSUE TITLE
[Question] 2024-2025 Schedules

### ISSUE THREAD

**Issue by Hokkaydo** [ADE-Scheduler/ADE-Scheduler#1055]
Hello,
Thanks for the great work you have done here!

More than one of us is wondering if support for the 2024-2025 academic year will be added soon.
I would be happy to help you if you could indicate roughly what needs to be changed.
The UCLouvain planner is still a pain in the ass :cry:

**Comment by SnaKyEyeS** [comment]
Il n'y a malheureusement rien à faire, voir #1050 :/
Sorry !

**Comment by Hokkaydo** [comment]
Pas de souci, merci !
