### ISSUE TITLE
Better error message banners

### ISSUE THREAD

**Issue by jeertmans** [ADE-Scheduler/ADE-Scheduler#454]
**Is your feature request related to a problem? Please describe.**
The current error message banner that pops up on the website has it message hard-coded into the HTML pages.
This means the message will not change no matter what the error is.

**Describe the solution you'd like**
Errors that are raised by Python are handled via our error handlers, and we can give a better error message to be displayed.
The error message should be given by Python when possible.

This is already the case of errors related to ADE, but the message is not used.

**Comment by ayush714** [comment]
Can you describe the lines of code??

**Comment by jeertmans** [comment]
Hi @ayush714 , thanks for you interest!

The goal is to replace error messages in the `.html` files, such as this one:

https://github.com/SnaKyEyeS/ADE-Scheduler/blob/64cddef1e34c03234e94c772d5f09e35e0c6e030/templates/calendar.html#L616-L619

With the error message sent by the error handlers, e.g.:

https://github.com/SnaKyEyeS/ADE-Scheduler/blob/64cddef1e34c03234e94c772d5f09e35e0c6e030/app.py#L282-L295

I think it can be solved by (1) creating a new error-message variable in the `.js` documents, (2) assigning it to the message in the catch statement (see example below), and (3) display its content in the `.html` files.

https://github.com/SnaKyEyeS/ADE-Scheduler/blob/64cddef1e34c03234e94c772d5f09e35e0c6e030/static/js/calendar.js#L309-L312

**Comment by RaviAnand111** [comment]
I can do it with javascript not python, would that work ?

**Comment by jeertmans** [comment]
Hi @RaviAnand111 , I am glad you are considering helping us !
Yes you can do it in JavaScript. The Python part is already working but could just use more error messages. This means you can start by only modifying JavaScript code.
