### ISSUE TITLE
Adding Yellow color to respect third main color principe

### ISSUE THREAD

**Issue by vinztheprinze99** [ADE-Scheduler/ADE-Scheduler#616]
This year I realize that I have meany type of events that I'd like to represent in the scheduler. During my management of my personal Agenda, I saw that there are 10 colors available in the app.  Some colors are shade of others but I didn't found the yellow color.

In order to add the third primary color (Yellow) I try locally to add event with several shade of yellow and I found this type : Bright Yellow - #FFEA00 which the render is pretty nice. So I think that this color might be added in the back-end possibilities.

Of course I would be more than happy to do the changes suggested.

Thanks for your futur answer and your point of view on it.

**Comment by jeertmans** [comment]
Hello @vinztheprinze99 , thanks for suggesting ! Do you have a screenshot to preview what you are referring to ?

**Comment by vinztheprinze99** [comment]
Hello @jeertmans,

Something like this color, that seems to be efficient :

![Capture](https://user-images.githubusercontent.com/71381281/141329058-c1902f61-359f-4aef-8582-06c1d8165bc1.JPG)

It might be changed in the file = https://github.com/ADE-Scheduler/ADE-Scheduler/blob/main/backend/schedules.py 

by adding (#ffff64) in the color_palette table. 

Thanks for your answer !

**Comment by jeertmans** [comment]
Thanks @vinztheprinze99. How do you see the color being introduced into the palette ? By replacing any other color, by replacing the other yellow-ish (the fifth in the default palette), or by extending the palette to contain 11 colors ?
One another important aspect is that we give care to producing a tool that appears great to most users. And this includes people with color blindness. In this regard, the luminosity of each color is significant to distinguish them (I haven't tested here).

**Comment by vinztheprinze99** [comment]
Hello @jeertmans , 

On my point of view, due to the actual yellow color (#ebcb8b") we might replace it by the new one. I think that add something closer to original Yellow is a good idea. The color #ffff64 is pretty visible for the people with color blindness and maintain user friendly interface.

**Comment by jeertmans** [comment]
Hello @vinztheprinze99, I did a rapid preview of what your suggested changes would reflect on a basic schedule.
Is it what you were referring to?
![before](https://user-images.githubusercontent.com/27275099/141642480-fa4e829b-54fc-4b87-acd7-b920b5c2d0f5.png)
![after](https://user-images.githubusercontent.com/27275099/141642486-d8b305cc-2d07-4d07-bb83-4b3b8d54557b.png)

**Comment by vinztheprinze99** [comment]
Hello, @jeertmans 

After looking for this shade of yellow it appears that is to "flash" to be visible to people with color blindness. 

I tried another shade that is more "smooth" and that I think is more visible. 
![ONe](https://user-images.githubusercontent.com/71381281/141644821-bff0ebca-0e9e-4580-9d5d-523a64b58a91.JPG)

Gives : 

![two](https://user-images.githubusercontent.com/71381281/141644829-a27ea089-655b-432d-a7ac-db504fb59790.JPG)

Please give me your feedback on it ( Color : 
rgb(250, 240, 140) - #faf08c ) 

Best regards.

**Comment by jeertmans** [comment]
Indeed, I agree with you, and it looks much better to me! Maybe you can propose a pull request?
Then, I will see with the other maintainers what they think about this.

**Comment by vinztheprinze99** [comment]
Hello @jeertmans, This is my pull request : https://github.com/ADE-Scheduler/ADE-Scheduler/pull/628

Thanks for your answer, 

best regards, Vincent.
