### ISSUE TITLE
French typos on Help and Contribute pages

### ISSUE THREAD

**Issue by LouisLabbe** [ADE-Scheduler/ADE-Scheduler#651]
Hello,

While browsing the project website I noticed several typos on the "Help" and "Contribute" pages/tabs in the french version. I won't quote all of them below but for example on the "Help" page there are: importer->importé, mise-à-jour->mise à jour, dans un délais->dans un délai, etc.

Obviously, I would be happy to correct these spelling mistakes.

**Comment by LouisLabbe** [comment]
I have read the tutorial provided and how to contribute to the project but I was wondering since these errors are only in the help-fr.json and contribute-fr.json files in the static/text folder (and not in the code or in the translations/LC_MESSAGES/messages.po file which would require a build), if I should really build and run the whole project for some careful deletion and addition of letters in the static json files. Thanks for your answer.

**Comment by jeertmans** [comment]
Hello @LouisLabbe, thanks for proposing your help. If you know which file to modify (which I assume reading your comment), you can just propose a PR with relevant modifications, and I will build it on my computer to test it.
