### ISSUE TITLE
bug date nouvel an

### ISSUE THREAD

**Issue by NoxTheXelor** [ADE-Scheduler/ADE-Scheduler#938]
Erreur au niveau des dates lié au nouvel an (juste décembre et janvier) en affichage mensuel (voir colonne dimanche) 
Le bug se corrige quand on zoome (ctrl + "+" ) ou dezoom mais réapparait quand on raffraichit la page

Side info : 
navigateur utilisé : Brave version v1.46.144 (Dec 14, 2022)
![image](https://user-images.githubusercontent.com/26748640/209829672-d9302651-489a-4ae2-b3c1-35acb5a566a3.png)

**Comment by jeertmans** [comment]
Bonjour @NoxTheXelor, merci pour ton message :)

Je pense que l’erreur est un bug d’affichage lié à ton navigateur et à FullCalendar (outil que nous utilisons pour afficher le calendrier).
Chez moi, tout est ok.

Pourrais-tu essayer avec un autre ordinateur et/ou un autre navigateur internet ?
Merci d’avance !
